### ISSUE TITLE
invalid URL?

### ISSUE THREAD

**Issue by 4chana** [greyivy/plex-letterboxd#3]
i'm a total novice at this so i apologize if this has a simple answer, i keep getting "[ERR_INVALID_URL]" and can't figure out how to fix it:

```
Node.js v20.16.0
Myname-MacBook-Pro:plex-letterboxd myname$ node ./index.js --ip my.ip.address --username myname /Users/myname/Desktop/letterboxd.txt
Processing list "https://letterboxd.com/dave/list/official-top-250-narrative-feature-films/"
Failed processing list "https://letterboxd.com/dave/list/official-top-250-narrative-feature-films/": Invalid URL
TypeError [ERR_INVALID_URL]: Invalid URL
    at Url.parse (node:url:416:17)
    at Object.urlParse [as parse] (node:url:141:13)
    at PlexAPI._request (/Users/myname/plex-letterboxd/node_modules/plex-api/lib/api.js:176:18)
    at PlexAPI.query (/Users/myname/plex-letterboxd/node_modules/plex-api/lib/api.js:72:17)
    at processList (file:///Users/myname/plex-letterboxd/index.js:68:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (file:///Users/myname/plex-letterboxd/index.js:148:4) {
  code: 'ERR_INVALID_URL',
  input: 'http://myipaddress :32400/'
}

```

tried with different list URLs in the txt file and am getting the same results every time. any advice? thank you!

**Comment by arhoads** [comment]
It looks like you didn't fill in your Plex IP. You can try `--ip localhost` if it is running on the same computer.
